{% set name = "ocha-anticipy" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb15fa4ef6e740ae3c14ec855053bfc945649305aabd437fb6122791581a63db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - cdsapi
    - cfgrib
    - cftime
    - geopandas
    - hdx-python-api >=5.6.4
    - hdx-python-country
    - netcdf4
    - numpy
    - pydantic
    - python-dateutil
    - pyyaml
    - rasterio
    - requests
    - rioxarray
    - wrapt
    - xarray

test:
  imports:
    - ochanticipy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OCHA-DAP/ocha-anticipy
  summary: Access data for anticipating humanitarian risk
  description: |
    OCHA AnticiPy is a Python library for simple downloading and 
    processing of data related to the anticipation of humanitarian 
    risk, from climate observations and forecasts to food insecurity.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://ocha-anticipy.readthedocs.io/
  dev_url: https://github.com/OCHA-DAP/ocha-anticipy

extra:
  recipe-maintainers:
    - turnerm
    - caldwellst
